# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/huyquang/huyquang/Company/thu-cuc/resources/uis/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(884, 586)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox.setStyleSheet("background: white;\n"
"border: 2px solid black;\n"
"border-radius: 5px;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.qline_num_camera = QtWidgets.QLineEdit(self.groupBox)
        self.qline_num_camera.setGeometry(QtCore.QRect(10, 30, 113, 21))
        self.qline_num_camera.setObjectName("qline_num_camera")
        self.btn_create_camera = QtWidgets.QPushButton(self.groupBox)
        self.btn_create_camera.setGeometry(QtCore.QRect(130, 30, 50, 21))
        self.btn_create_camera.setObjectName("btn_create_camera")
        self.btn_start = QtWidgets.QPushButton(self.groupBox)
        self.btn_start.setGeometry(QtCore.QRect(10, 70, 171, 32))
        self.btn_start.setObjectName("btn_start")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background: white;\n"
"border: 2px solid black;\n"
"border-radius: 5px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_create_camera.setText(_translate("MainWindow", "Create"))
        self.btn_start.setText(_translate("MainWindow", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
